#!/usr/bin/env python
import getpass
import telnetlib


user = raw_input("Username: ")
password = getpass.getpass()

file = open("ip.txt")

for line in file:
        print ("getting start-config: " + (line))
        host = line.strip()
        tn = telnetlib.Telnet(host)

        tn.read_until("Username: ")
        tn.write(user + "\n")
        if password:
                tn.read_until("Password: ")
                tn.write(password + "\n")

        #tn.write("cisco\n")
        #tn.write("enable\n")
        tn.write("terminal length 0 \n" )
        tn.write("enable\n")
        tn.write("cisco\n")
        tn.write("show run\n")
        tn.write("exit\n")

        readoutput = tn.read_all()
        saveoutput = open("switch" + host, "w")
        saveoutput.write(readoutput)
        saveoutput.close
